name: {{app_name.snakeCase()}}
description: "Généré par Forge AGI (brick mobile_app_base)"
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter: 
    sdk: flutter
  hooks_riverpod: ^2.5.1
  go_router: ^14.2.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  http: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true
