name: android-build

on:
  workflow_dispatch:
  push:
    branches: [ main, mvp/mobile_v0.2 ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
      - name: Flutter Analyze
        run: flutter analyze
      - name: Run Tests
        run: flutter test --machine > test_report.json || true
      - name: Build APK (release unsigned)
        run: flutter build apk --release
      - name: APK SHA256 & size
        run: |
          sha256sum build/app/outputs/flutter-apk/app-release.apk > apk_sha256.txt
          stat --printf="%s" build/app/outputs/flutter-apk/app-release.apk > apk_size_bytes.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            test_report.json
            apk_sha256.txt
            apk_size_bytes.txt
